### ISSUE TITLE
Problem with .rtf files containing special characters in the repo

### ISSUE THREAD

**Issue by ghost** [wombyz/custom-knowledge-chatbot#5]
Hello,

I encountered an issue while trying to clone the custom-knowledge-chatbot repository on a Windows machine. The issue is related to .rtf files with special characters (specifically question marks) in their file names. Windows does not allow the use of certain special characters in file names, including question marks, which leads to an error during the cloning process.

Here is an example of an invalid file path causing the issue:
custom-knowledge-chatbot/asos/Can you tell me more about your ASOS Premier service in Saudi Arabia? .rtf

I suggest updating the file names by removing or replacing the special characters (e.g., replacing the question mark with a hyphen) to make the repository compatible with Windows. This change would make it easier for Windows users to clone and work with your repository without encountering errors.

Thank you for your attention to this matter, and please let me know if you need any further information or assistance.

Very truly yours,

Reno Fernandez

PS:  This email was generated using GPT-4.  I figured you would appreciate that.

**Comment by wombyz** [comment]
Hi mate, 

I'd just change the file names then, not a big deal I just copied them from the website!

Thanks for the support,

Liam

**Comment by ghost** [comment]
You are a huge inspiration, and the chief reason why I am getting into this stuff.  But I am still pretty new.  ChatGPT is allowing me to code quite a bit beyond my actual skill level, and I am largely relying on its advice in trying to clone the repo.  Accordingly, I have a dumb question…  How do I actually do it?  Or is it easier to copy from the same website?  PS:  I don’t know the website.  And thank you so much!
