### ISSUE TITLE
When i create an index of documents

### ISSUE THREAD

**Issue by baberibrar** [wombyz/custom-knowledge-chatbot#6]
when I run the index of documents cell then returns an error 
ValueError: The constructor now takes in a list of Node objects. Since you are passing in a list of Document objects, please use `from_documents` instead.
<img width="1088" alt="Screenshot 2023-03-30 at 9 01 24 PM" src="https://user-images.githubusercontent.com/61284156/228896020-7ab8a360-e833-4a07-b230-91cd0ad84cd8.png">

**Comment by mychaelangelo** [comment]
you should update from

index = GPTSimpleVectorIndex(documents)

to

index = GPTSimpleVectorIndex.from_documents(documents)

see details here https://gpt-index.readthedocs.io/en/latest/index.html
